export const en_us = {
  subtitulo: '',
  linguagens: 'languages',
  matematica: 'math',
  ciencias: 'science',
  humanas: 'human',
  lp: 'Letters',
  arte: 'Art',
  quantidade: 'Amount',
  formasGeometricas: 'Geometric Shapes',
  corpoHumano: 'Human Body',
  natureza: 'Nature',
  geografia: 'Geography',
  historia: 'History',
  jogoAlfabetoDescricao: "Let's add the apples to the tree",
  jogoAlfabeto: 'Alphabet with apples game',
  jogoAlfabetoDica: 'Drag the letters to complete the alphabet',
  jogoIniciaisDescricao: "Let's complete the word",
  jogoIniciais: 'Initials game',
  jogoIniciaisDica: 'Click on the missing letter',
  jogoCoresFrutasDescricao: "Let's connect the fruits and their colors",
  jogoCoresFrutas: "Fruits' color game",
  jogoCoresFrutasDica: 'Drag the colors to the fruits',
  jogoCoresDescricao: "Let's identify the names of the colors",
  jogoCores: "Colors' initials game",
  jogoCoresDica: 'Click on the missing letter',
  jogoCoracoesDescricao: "Let's count hearts",
  jogoCoracoes: 'Counting hearts game',
  jogoCoracoesDica: 'Click the right amount of hearts',
  jogoQuantidadesDescricao: "Let's mark how many we have",
  jogoQuantidades: 'Identify the amount game',
  jogoQuantidadesDica: 'Click on the squares to represent the quantity',
  jogoQtdeFormasDescricao: "Let's count the shapes",
  jogoQtdeFormas: 'Counting the shapes game',
  jogoQtdeFormasDica: 'Drag the shapes to their quantity',
  jogoEncaixarFormasDescricao: "Let's fit the shapes",
  jogoEncaixarFormas: 'Fitting shapes game',
  jogoEncaixarFormasDica: 'Drag shapes to their shadows',
  jogoCorpoHumanoDescricao: "Let's identify the body parts",
  jogoCorpoHumano: 'Identify body parts game',
  jogoCorpoHumanoDica: 'Drag the parts to the correct position',
  jogoAcessoriosDescricao: "Let's add the accessories",
  jogoAcessorios: "Add the accessories game",
  jogoAcessoriosDica: 'Drag the pieces to the correct position',
  jogoSeresVivosDescricao: "Let's identify the names of the living",
  jogoSeresVivos: "Living's initials game",
  jogoSeresVivosDica: 'Click on the missing letter',
  jogoFilhotesDescricao: "Let's take the puppies to their parents",
  jogoFilhotes: "Puppies' game",
  jogoFilhotesDica: 'Drag the puppies to their parents',
  jogoClimaDescricao: "Let's identify the weather",
  jogoClima: "Weather's game",
  jogoClimaDica: 'Click on the missing letter',
  jogoVeiculosDescricao: "Let's connect each vehicle to its means of transport",
  jogoVeiculos: 'Transports game',
  jogoVeiculosDica: 'Drag vehicles to places',
  jogoFolcloreDescricao: "Let's identify the characters of Brazilian folklore",
  jogoFolclore: 'Folklore game',
  jogoFolcloreDica: 'Click on the missing letter',
  jogoMeiosComunicacaoDescricao: "Let's identify the media being used",
  jogoMeiosComunicacao: "Media's game",
  jogoMeiosComunicacaoDica: "Drag the media to where it's being used",
  rankingNome: 'Name',
  rankingPontos: 'Points',
  rankingNivel: 'Level',
  tooltipSave: 'Load Player',
  tooltipPlay: 'Create New Player',
  selecionarJogador: 'Select a Player',
  inserirNome: 'Insert your Name',
  escolherAvatar: 'Choose your Avatar',
  nenhumJogadorDisponivel: "There isn't any available players! How about we make one?",
  jogosEducativos: 'Educative Games'
}
