export const es_es = {
  subtitulo: 'AprenderEsDivertido',
  linguagens: 'idiomas',
  matematica: 'matemáticas',
  ciencias: 'ciencias',
  humanas: 'humanas',
  lp: 'Letras',
  arte: 'Arte',
  quantidade: 'Cantidad',
  formasGeometricas: 'Formas Geométricas',
  corpoHumano: 'Cuerpo Humano',
  natureza: 'Naturaleza',
  geografia: 'Geografía',
  historia: 'Historia',
  jogoAlfabetoDescricao: 'Pongamos las manzanas en el árbol',
  jogoAlfabeto: 'Juego de letras con manzanas',
  jogoAlfabetoDica: 'Arrastra las letras para completar el abecedario',
  jogoIniciaisDescricao: 'Completemos la palabra',
  jogoIniciais: 'Juego de iniciales',
  jogoIniciaisDica: 'Haga clic en la letra que falta',
  jogoCoresFrutasDescricao: 'Vamos a conectar las frutas y sus colores',
  jogoCoresFrutas: 'Juego de colores de frutas',
  jogoCoresFrutasDica: 'Arrastra los colores a las frutas',
  jogoCoresDescricao: 'Vamos a identificar los nombres de los colores',
  jogoCores: 'Juego de iniciales de colores',
  jogoCoresDica: 'Haga clic en la letra que falta',
  jogoCoracoesDescricao: 'Contemos corazones',
  jogoCoracoes: 'Juego de contar corazones',
  jogoCoracoesDica: 'Haga clic en la cantidad correcta de corazones',
  jogoQuantidadesDescricao: 'Vamos a marcar cuantos tenemos',
  jogoQuantidades: 'Juego de identificación de cantidades',
  jogoQuantidadesDica: 'Haga clic en los cuadrados para representar la cantidad',
  jogoQtdeFormasDescricao: 'Contemos las formas',
  jogoQtdeFormas: 'Juego de contar formas',
  jogoQtdeFormasDica: 'Arrastra las formas a su cantidad',
  jogoEncaixarFormasDescricao: 'Ajustemos las formas',
  jogoEncaixarFormas: 'Juego de ajuste de formas',
  jogoEncaixarFormasDica: 'Arrastra formas a sus sombras',
  jogoCorpoHumanoDescricao: 'Identifiquemos las partes del cuerpo',
  jogoCorpoHumano: 'Juego para identificar partes del cuerpo',
  jogoCorpoHumanoDica: 'Arrastre partes a la posición correcta',
  jogoAcessoriosDescricao: 'Vamos a agregar los accesorios',
  jogoAcessorios: 'Juego para añadir accesorios',
  jogoAcessoriosDica: 'Arrastra las piezas a la posición correcta',
  jogoSeresVivosDescricao: 'Vamos a identificar los nombres de los seres vivos',
  jogoSeresVivos: 'Juego de iniciales de seres vivos',
  jogoSeresVivosDica: 'Haz clic en la letra que falta',
  jogoFilhotesDescricao: 'Llevemos los cachorros con sus padres',
  jogoFilhotes: 'Juego de cachorros',
  jogoFilhotesDica: 'Arrastra los cachorros hasta sus padres',
  jogoClimaDescricao: 'Identifiquemos los climas',
  jogoClima: 'Juego climático',
  jogoClimaDica: 'Arrastra elementos al marco derecho',
  jogoVeiculosDescricao: 'Vamos a conectar cada vehículo a su medio de transporte',
  jogoVeiculos: 'Juego de transporte',
  jogoVeiculosDica: 'Arrastra vehículos a lugares',
  jogoFolcloreDescricao: 'Identifiquemos los personajes del folclore brasileño',
  jogoFolclore: 'Juego folklórico',
  jogoFolcloreDica: 'Haga clic en la letra que falta',
  jogoMeiosComunicacaoDescricao: 'Identifiquemos los medios de comunicación utilizados',
  jogoMeiosComunicacao: 'Juego multimedia',
  jogoMeiosComunicacaoDica: 'Haga clic en la letra que falta',
  rankingNome: 'Nombre',
  rankingPontos: 'Puntos',
  rankingNivel: 'Nível',
  tooltipSave: 'Seleccionar Jugador',
  tooltipPlay: 'Registrar Nuevo Jugador',
  selecionarJogador: 'Seleccionar un Jugador',
  inserirNome: 'Ingrese su Nombre',
  escolherAvatar: 'Elige tu Avatar',
  nenhumJogadorDisponivel: '¡No hay jugadores disponibles! ¿Qué tal si creamos uno?',
  jogosEducativos: 'Juegos Educativos',
  bemVindo: 'Bienvenido',
  botaoVoltar:'Atrás',
  logoff: 'Cerrar sesión',
  nivel: 'Nivel',
  pontos: 'Puntos',
  parabens: '¡Felicidades! Tú lo hiciste',
  acertou: '¡Muy bien!',
  errou: 'Inténtalo de nuevo',
  reload: 'Jugar de nuevo',
  naoDeuCerto: '¡No funcionó! ¿Lo intentamos de nuevo?',
  erroExcluir: '¡Error al eliminar jugador!',
  escolherJogador: 'Elegir jugador',
  excluirJogador: 'Eliminar jugador',
  posicao: 'º lugar',
  //1.1
  palavraBola: "_ELOTA",
  respostaBola: "P",
  palavraAviao: "_VIÓN",
  respostaAviao: "A",
  palavraCasa: "_OGAR",
  respostaCasa: "H",
  palavraMacaco: "_ONO",
  respostaMacaco: "M",
  palavraLua: "_UNA",
  respostaLua: "L",
  palavraOvo: "_UEVO",
  respostaOvo: "H",
  palavraEstrela: "_STRELLA",
  respostaEstrela: "E",
  palavraPato: "_ATO",
  respostaPato: "P",
  //1.4
  palavraVermelho: "_OJO",
  respostaVermelho: "R",
  palavraVerde: "_ERDE",
  respostaVerde: "V",
  palavraAzul: "_ZUL",
  respostaAzul: "A",
  palavraRoxo: "_ÚRPURA",
  respostaRoxo: "P",
  palavraRosa: "_OSA",
  respostaRosa: "R",
  palavraAmarelo: "_MARILLO",
  respostaAmarelo: "A",
  palavraMarrom: "_ARRÓN",
  respostaMarrom: "M",
  palavraPreto: "_EGRO",
  respostaPreto: "N",
  //3.3
  palavraHumano: "_UMANO",
  respostaHumano: "H",
  palavraBorboleta: "_ARIPOSA",
  respostaBorboleta: "M",
  palavraTartaruga: "_ORTUGA",
  respostaTartaruga: "T",
  palavraCogumelo: "_HAMPIÑÓN",
  respostaCogumelo: "C",
  palavraPeixe: "_EZ",
  respostaPeixe: "P",
  palavraSapo: "_ANA",
  respostaSapo: "R",
  palavraFlor: "_LOR",
  respostaFlor: "F",
  palavraBaleia: "_ALLENA",
  respostaBaleia: "B",
  //4.4
  palavraTelevisao: "_ELEVISIÓN",
  respostaTelevisao: "T",
  palavraRadio: "_ADIO",
  respostaRadio: "R",
  palavraJornal: "_ERIÓDICO",
  respostaJornal: "P",
  palavraRevista: "_EVISTA",
  respostaRevista: "R",
  palavraCinema: "_INE",
  respostaCinema: "C",
  palavraTeatro: "_EATRO",
  respostaTeatro: "T",
  palavraCelular: "_ELÉFONO",
  respostaCelular: "T",
  palavraComputador: "_OMPUTADORA",
  respostaComputador: "C",
  //fim jogos
  desativarSom: 'desactivar el sonido',
  positivo1: '¡Felicidades! Lo hiciste bien',
  positivo2: '¡Muy bien!',
  positivo3: '¡Buen trabajo!',
  positivo4: '¡Lo he logrado!',
  positivo5: '¡Lo estás haciendo muy bien!',
  negativo1: '¡Ups! Intentar otra vez',
  negativo2: '¿Lo intentamos de nuevo?',
  negativo3: '¡Oh, no! No es la respuesta correcta',
  negativo4: '¡Sigue intentándolo!',
  negativo5: '¡No te desanimes, ya casi es!',
  observando1: 'Humm',
  observando2: 'Continuar...',
  observando3: 'solo estoy mirando',
  concluiu1: '¡Guau! ¡Lo hiciste!',
  concluiu2: '¡Felicidades! ¡Todo salió bien!',
  concluiu3: '¡Increíble! ¡Eres increíble!',
  voltar: 'volver',
  seuAvatar: 'tu avatar',
  seuNome: 'tu nombre es ',
  sairDaConta: 'sair de cuenta',
  portugues: 'portugués',
  espanhol: 'español',
  ingles: 'inglés',
  confirmarExclusao: '¿Confirmar eliminar jugador?',
  confirmacaoExclusao: 'jugador excluido',
  //acessorios
  meias: 'calcetines',
  laco: 'bucle',
  oculos: 'gafas',
  anel: 'anillo',
  saia: 'falda',
  sapatilha: 'zapatilla',
  brincos: 'pendientes',
  blusa: 'blusa',
  cabelos: 'pelo',
  orelhas: 'orejas',
  olhos: 'ojos',
  maos: 'manos',
  tronco: 'torso',
  pernas: 'piernas',
  pes: 'pies',
  //filhotes
  cachorrinho: 'perrito',
  leaozinho: 'pequeño león',
  ursinho: 'osito',
  pintinho: 'pollito',
  cachorro: 'perro',
  leao: 'león',
  urso: 'oso',
  galo: 'gallo',
  //corpo humano
  cabeca: 'cabeza',
  nariz: 'nariz',
  boca: 'boca',
  braco: 'brazo',
  joelho: 'rodilla',
  perna: 'pierna',
  //clima
  sol: 'clima soleado',
  chuva: 'tiempo lluvioso',
  objetos: 'objetos',
  biquini: 'bikini',
  bone: 'gorra',
  capaChuva: 'impermeable',
  casaco: 'abrigo',
  chinelo: 'zapatillas',
  galochas: 'chanclos',
  guardaChuva: 'paraguas',
  oculosSol: 'gafas de sol',
  //veiculos
  carro: 'coche',
  trem: 'tren',
  barco: 'barco',
  aviao: 'avión',
  mar: 'mar',
  ceu: 'cielo',
  estrada: 'camino',
  trilhos: 'rieles',
  //cores frutas
  amarelo: 'amarillo',
  verde: 'verde',
  vermelho: 'rojo',
  roxo: 'púrpura',
  banana: 'plátano',
  morango: 'fresa',
  uva: 'uva',
  pera: 'pera',
  //formas
  quadrado: 'cuadrado',
  circulo: 'círculo',
  retangulo: 'rectángulo',
  triangulo: 'triángulo',
}
