export const es_es = {
  subtitulo: 'AprenderEsDivertido',
  linguagens: 'idiomas',
  matematica: 'matemáticas',
  ciencias: 'ciencias',
  humanas: 'humanas',
  lp: 'Letras',
  arte: 'Arte',
  quantidade: 'Cantidad',
  formasGeometricas: 'Formas Geométricas',
  corpoHumano: 'Cuerpo Humano',
  natureza: 'Naturaleza',
  geografia: 'Geografía',
  historia: 'Historia',
  jogoAlfabetoDescricao: 'Pongamos las manzanas en el árbol',
  jogoAlfabeto: 'Juego de letras con manzanas',
  jogoAlfabetoDica: 'Arrastra las letras para completar el abecedario',
  jogoIniciaisDescricao: 'Completemos la palabra',
  jogoIniciais: 'Juego de iniciales',
  jogoIniciaisDica: 'Haga clic en la letra que falta',
  jogoCoresFrutasDescricao: 'Vamos a conectar las frutas y sus colores',
  jogoCoresFrutas: 'Juego de colores de frutas',
  jogoCoresFrutasDica: 'Arrastra los colores a las frutas',
  jogoCoresDescricao: 'Vamos a identificar los nombres de los colores',
  jogoCores: 'Juego de iniciales de colores',
  jogoCoresDica: 'Haga clic en la letra que falta',
  jogoCoracoesDescricao: 'Contemos corazones',
  jogoCoracoes: 'Juego de contar corazones',
  jogoCoracoesDica: 'Haga clic en la cantidad correcta de corazones',
  jogoQuantidadesDescricao: 'Vamos a marcar cuantos tenemos',
  jogoQuantidades: 'Juego de identificación de cantidades',
  jogoQuantidadesDica: 'Haga clic en los cuadrados para representar la cantidad',
  jogoQtdeFormasDescricao: 'Contemos las formas',
  jogoQtdeFormas: 'Juego de contar formas',
  jogoQtdeFormasDica: 'Arrastra las formas a su cantidad',
  jogoEncaixarFormasDescricao: 'Ajustemos las formas',
  jogoEncaixarFormas: 'Juego de ajuste de formas',
  jogoEncaixarFormasDica: 'Arrastra formas a sus sombras',
  jogoCorpoHumanoDescricao: 'Identifiquemos las partes del cuerpo',
  jogoCorpoHumano: 'Juego para identificar partes del cuerpo',
  jogoCorpoHumanoDica: 'Arrastre partes a la posición correcta',
  jogoAcessoriosDescricao: 'Vamos a agregar los accesorios',
  jogoAcessorios: 'Juego para añadir accesorios',
  jogoAcessoriosDica: 'Arrastra las piezas a la posición correcta',
  jogoSeresVivosDescricao: 'Vamos a identificar los nombres de los seres vivos',
  jogoSeresVivos: 'Juego de iniciales de seres vivos',
  jogoSeresVivosDica: 'Haz clic en la letra que falta',
  jogoFilhotesDescricao: 'Llevemos los cachorros con sus padres',
  jogoFilhotes: 'Juego de cachorros',
  jogoFilhotesDica: 'Arrastra los cachorros hasta sus padres',
  jogoClimaDescricao: 'Identifiquemos los climas',
  jogoClima: 'Juego climático',
  jogoClimaDica: 'Arrastra elementos al marco derecho',
  jogoVeiculosDescricao: 'Vamos a conectar cada vehículo a su medio de transporte',
  jogoVeiculos: 'Juego de transporte',
  jogoVeiculosDica: 'Arrastra vehículos a lugares',
  jogoFolcloreDescricao: 'Identifiquemos los personajes del folclore brasileño',
  jogoFolclore: 'Juego folklórico',
  jogoFolcloreDica: 'Haga clic en la letra que falta',
  jogoMeiosComunicacaoDescricao: 'Identifiquemos los medios de comunicación utilizados',
  jogoMeiosComunicacao: 'Juego multimedia',
  jogoMeiosComunicacaoDica: 'Haga clic en la letra que falta',
  rankingNome: 'Nombre',
  rankingPontos: 'Puntos',
  rankingNivel: 'Nível',
  tooltipSave: 'Seleccionar Jugador',
  tooltipPlay: 'Registrar Nuevo Jugador',
  selecionarJogador: 'Seleccionar un Jugador',
  inserirNome: 'Ingrese su Nombre',
  escolherAvatar: 'Elige tu Avatar',
  nenhumJogadorDisponivel: '¡No hay jugadores disponibles! ¿Qué tal si creamos uno?',
  jogosEducativos: 'Juegos Educativos',
  bemVindo: 'Bienvenido',
  botaoVoltar:'Atrás',
  logoff: 'Cerrar sesión',
  nivel: 'Nivel',
  pontos: 'Puntos',
  parabens: '¡Felicidades! Tú lo hiciste',
  acertou: '¡Muy bien!',
  errou: 'Inténtalo de nuevo',
  reload: 'Jugar de nuevo',
  naoDeuCerto: '¡No funcionó! ¿Lo intentamos de nuevo?',
  erroExcluir: '¡Error al eliminar jugador!',
  escolherJogador: 'Elegir jugador',
  excluirJogador: 'Eliminar jugador',
  posicao: 'º lugar',
}
