export const es_es = {
  subtitulo: 'AprenderEsDivertido',
  pesquisa: 'Búsqueda',
  linguagens: 'idiomas',
  matematica: 'matemáticas',
  ciencias: 'ciencias',
  humanas: 'humanas',
  lp: 'Letras',
  arte: 'Arte',
  quantidade: 'Cantidad',
  formasGeometricas: 'Formas Geométricas',
  corpoHumano: 'Cuerpo Humano',
  natureza: 'Naturaleza',
  geografia: 'Geografía',
  historia: 'Historia',
  jogoCorpoHumanoDescricao: 'Identifiquemos las partes del cuerpo',
  jogoCorpoHumanoDica: 'Arrastre partes a la posición correcta',
  jogoAcessoriosDescricao: 'Vamos a agregar los accesorios',
  jogoAcessoriosDica: 'Arrastra las piezas a la posición correcta',
  jogoQuantidadesDescricao: 'Vamos a marcar cuantos tenemos',
  jogoQuantidadesDica: 'Haga clic en los cuadrados para representar la cantidad',
  jogoCoracoesDescricao: 'Contemos corazones',
  jogoCoracoesDica: 'Haga clic en la cantidad correcta de corazones',
  jogoIniciaisDescricao: 'Completemos la palabra',
  jogoIniciaisDica: 'Haga clic en la letra que falta',
  jogoQtdeFormasDescricao: 'Contemos las formas',
  jogoQtdeFormasDica: 'Arrastra las formas a su cantidad',
  jogoAlfabetoDescricao: 'Pongamos las manzanas en el árbol',
  jogoAlfabetoDica: 'Arrastra las letras para completar el abecedario',
  rankingNome: 'Nombre',
  rankingPontos: 'Puntos',
  rankingNivel: 'Nível',
  jogoEncaixarFormasDescricao: 'Ajustemos las formas',
  jogoEncaixarFormasDica: 'Arrastra formas a sus sombras',
  jogoCoresFrutasDescricao: 'Vamos a conectar las frutas y sus colores',
  jogoCoresFrutasDica: 'Arrastra los colores a las frutas',
  jogoAnimaisDescricao: 'Vinculemos cada animal con su comida',
  jogoAnimaisDica: 'Arrastra los animales a la comida',
  jogoVeiculosDescricao: 'Vamos a conectar cada vehículo a su medio de transporte',
  jogoVeiculosDica: 'Arrastra vehículos a lugares',
  jogoPlanetasDescricao: 'Vamos a identificar los nombres',
  jogoPlanetasDica: 'Arrastra los nombres a su correspondiente',
  jogoCoresDescricao: 'Vamos a identificar los nombres de los colores',
  jogoCoresDica: 'Haga clic en la letra que falta',
  jogoSeresVivosDescricao: 'Vamos a identificar los nombres de los seres vivos',
  jogoSeresVivosDica: 'Haz clic en la letra que falta',
  jogoFolcloreDescricao: 'Identifiquemos los personajes del folclore brasileño',
  jogoFolcloreDica: 'Haga clic en la letra que falta',
  jogoOndeEstaoDescricao: 'Vamos a identificar dónde están',
  jogoOndeEstaoDica: 'Arrastrar al lugar correcto',
  tooltipSave: 'Seleccionar Jugador',
  tooltipPlay: 'Registrar Nuevo Jugador',
  selecionarJogador: 'Seleccionar un Jugador',
  inserirNome: 'Ingrese su Nombre',
  escolherAvatar: 'Elige tu Avatar',
  nenhumJogadorDisponivel: '¡No hay jugadores disponibles! ¿Qué tal si creamos uno?',
  jogosEducativos: 'Juegos Educativos'
}
