export const pt_br = {
  subtitulo: 'AprenderÉDivertido',
  linguagens: 'linguagens',
  matematica: 'matemática',
  ciencias: 'ciências',
  humanas: 'humanas',
  lp: 'Letras',
  arte: 'Arte',
  quantidade: 'Quantidade',
  formasGeometricas: 'Formas Geométricas',
  corpoHumano: 'Corpo Humano',
  natureza: 'Natureza',
  geografia: 'Geografia',
  historia: 'História',
  jogoAlfabetoDescricao: 'Vamos colocar as maçãs na árvore',
  jogoAlfabeto: 'Jogo do alfabeto com maçãs',
  jogoAlfabetoDica: 'Arrastar as letras para completar o alfabeto',
  jogoIniciaisDescricao: 'Vamos completar a palavra',
  jogoIniciais: 'Jogo das iniciais',
  jogoIniciaisDica: 'Clicar na letra que está faltando',
  jogoCoresFrutasDescricao: 'Vamos ligar as frutas e suas cores',
  jogoCoresFrutas: 'Jogo das cores das frutas',
  jogoCoresFrutasDica: 'Arrastar as cores até as frutas',
  jogoCoresDescricao: 'Vamos identificar os nomes das cores',
  jogoCores: 'Jogo das iniciais das cores',
  jogoCoresDica: 'Clicar na letra que falta',
  jogoCoracoesDescricao: 'Vamos contar corações',
  jogoCoracoes: 'Jogo de contar corações',
  jogoCoracoesDica: 'Clicar na quantidade certa de corações',
  jogoQuantidadesDescricao: 'Vamos marcar quantos temos',
  jogoQuantidades: 'Jogo de identificar quantidades',
  jogoQuantidadesDica: 'Clicar nos quadrados para representar a quantidade',
  jogoQtdeFormasDescricao: 'Vamos contar as formas',
  jogoQtdeFormas: 'Jogo de contar as formas',
  jogoQtdeFormasDica: 'Arrastar as formas até sua quantidade',
  jogoEncaixarFormasDescricao: 'Vamos encaixar as formas',
  jogoEncaixarFormas: 'Jogo de encaixar as formas',
  jogoEncaixarFormasDica: 'Arrastar as formas até suas sombras',
  jogoCorpoHumanoDescricao: 'Vamos identificar as partes do corpo',
  jogoCorpoHumano: 'Jogo de identificar as partes do corpo',
  jogoCorpoHumanoDica: 'Arrastar as partes para a posição correta',
  jogoAcessoriosDescricao: 'Vamos adicionar os acessórios',
  jogoAcessorios: 'Jogo de adicionar os acessórios',
  jogoAcessoriosDica: 'Arrastar as peças para a posição correta',
  jogoSeresVivosDescricao: 'Vamos identificar os nomes dos seres vivos',
  jogoSeresVivos: 'Jogo das iniciais dos seres vivos',
  jogoSeresVivosDica: 'Clicar na letra que falta',
  jogoFilhotesDescricao: 'Vamos levar os filhotes aos seus pais',
  jogoFilhotes: 'Jogo dos filhotes',
  jogoFilhotesDica: 'Arrastar os filhotes até seus pais',
  jogoClimaDescricao: 'Vamos identificar os climas',
  jogoClima: 'Jogo do clima',
  jogoClimaDica: 'Arraste os itens para o quadro certo',
  jogoVeiculosDescricao: 'Vamos ligar cada veículo ao seu meio de transporte',
  jogoVeiculos: 'Jogo de transportes',
  jogoVeiculosDica: 'Arrastar os veículos até os lugares',
  jogoFolcloreDescricao: 'Vamos identificar os personagens do folclore brasileiro',
  jogoFolclore: 'Jogo do folclore',
  jogoFolcloreDica: 'Clicar na letra que falta',
  jogoMeiosComunicacaoDescricao: 'Vamos identificar os meios de comunicação utilizados',
  jogoMeiosComunicacao: 'Jogo dos meios de comunicação',
  jogoMeiosComunicacaoDica: 'Clicar na letra faltando',
  rankingNome: 'Nome',
  rankingPontos: 'Pontos',
  rankingNivel: 'Nível',
  tooltipSave: 'Selecionar Jogador',
  tooltipPlay: 'Cadastrar Novo Jogador',
  selecionarJogador: 'Selecione um Jogador',
  inserirNome: 'Insira seu Nome',
  escolherAvatar: 'Escolha seu Avatar',
  nenhumJogadorDisponivel: 'Não há nenhum jogador disponível! Que tal criarmos um?',
  jogosEducativos: 'Jogos Educativos',
  bemVindo: 'Bem vindo',
  botaoVoltar:'Voltar',
  logoff: 'Deslogar',
  nivel: 'Nível',
  pontos: 'Pontos',
  parabens: 'Parabéns! Você conseguiu',
  acertou: 'Muito bem!',
  errou: 'Tente novamente',
  reload: 'Jogar novamente',
  naoDeuCerto: 'Não deu certo! Vamos tentar de novo?',
  erroExcluir: 'Erro ao excluir jogador!',
  escolherJogador: 'Escolher jogador',
  excluirJogador: 'Excluir jogador',
  posicao: 'º Lugar',
  //1.1
  palavraBola: "_OLA",
  respostaBola: "B",
  palavraAviao: "_VIÃO",
  respostaAviao: "A",
  palavraCasa: "_ASA",
  respostaCasa: "C",
  palavraMacaco: "_ACACO",
  respostaMacaco: "M",
  palavraLua: "_UA",
  respostaLua: "L",
  palavraOvo: "_VO",
  respostaOvo: "O",
  palavraEstrela: "_STRELA",
  respostaEstrela: "E",
  palavraPato: "_ATO",
  respostaPato: "P",
  //1.4
  palavraVermelho: "_ERMELHO",
  respostaVermelho: "V",
  palavraVerde: "_ERDE",
  respostaVerde: "V",
  palavraAzul: "_ZUL",
  respostaAzul: "A",
  palavraRoxo: "_OXO",
  respostaRoxo: "R",
  palavraRosa: "_OSA",
  respostaRosa: "R",
  palavraAmarelo: "_MARELO",
  respostaAmarelo: "A",
  palavraMarrom: "_ARROM",
  respostaMarrom: "M",
  palavraPreto: "_RETO",
  respostaPreto: "P",
  //3.3
  palavraHumano: "_UMANO",
  respostaHumano: "H",
  palavraBorboleta: "_ORBOLETA",
  respostaBorboleta: "B",
  palavraTartaruga: "_ARTARUGA",
  respostaTartaruga: "T",
  palavraCogumelo: "_OGUMELO",
  respostaCogumelo: "C",
  palavraPeixe: "_EIXE",
  respostaPeixe: "P",
  palavraSapo: "_APO",
  respostaSapo: "S",
  palavraFlor: "_LOR",
  respostaFlor: "F",
  palavraBaleia: "_ALEIA",
  respostaBaleia: "B",
  //4.4
  palavraTelevisao: "_ELEVISÃO",
  respostaTelevisao: "T",
  palavraRadio: "_ÁDIO",
  respostaRadio: "R",
  palavraJornal: "_ORNAL",
  respostaJornal: "J",
  palavraRevista: "_EVISTA",
  respostaRevista: "R",
  palavraCinema: "_INEMA",
  respostaCinema: "C",
  palavraTeatro: "_EATRO",
  respostaTeatro: "T",
  palavraCelular: "_ELULAR",
  respostaCelular: "C",
  palavraComputador: "_OMPUTADOR",
  respostaComputador: "C",
}
